language: android

dist: trusty

install: true

jdk:
  - oraclejdk8

android:
  licenses:
    - 'android-sdk-license-.+'

script:
  - ./gradlew test build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
